# Generated by Django 4.2.11 on 2025-10-22 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Título')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug (URL)')),
                ('content', models.TextField(help_text='Contenido en HTML', verbose_name='Contenido HTML')),
                ('meta_description', models.CharField(blank=True, help_text='Para SEO (máx 160 caracteres)', max_length=160, verbose_name='Meta Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Activa?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creada el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizada el')),
            ],
            options={
                'verbose_name': 'Página',
                'verbose_name_plural': 'Páginas',
                'ordering': ['title'],
            },
        ),
    ]
